modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/rezonant/rezolve"

[[mods]]
modId="rezolve"
version="${file.jarVersion}"

displayName="Rezolve"
logoFile="logo.png"
displayURL="https://minecraft.curseforge.com/projects/rezolve"
description=""
authors="rezonant"
displayTest="MATCH_VERSION"
